apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-backend
  template:
    metadata:
      labels:
        app: golang-backend
    spec:
      containers:
      - name: golang-backend
        image: gcr.io/focal-rampart-437408/golang-backend
        ports:
        - containerPort: 8080